### ISSUE TITLE
Convenient virtual aliases special case

### ISSUE THREAD

**Issue by paulhenrich** [taoeffect/empress#65]
I had an idea for a special case of mail_virtual_aliases that would help me a lot (I have ~100 aliases that I want to all go to my main account). I'm currently working against a branch of Sovereign, but just found Empress.

``` yaml
main_aliases:
  - foo@example.net
  - quux@example.net
  - postmaster@example.net (?)
```

Thoughts on if this is worth doing in Empress?

**Comment by paulhenrich** [comment]
I am thinking that this could work along side of the suggested inference in #12. No need to manually identify name with primary key in either case as far as I can tell.

**Comment by taoeffect** [comment]
@paulhenrich Can you describe in a bit more detail what you'd like to do?

Empress already has a very simple way of defining `mail_virtual_aliases:`:

``` yml
mail_virtual_aliases:
  - root@yourdomain.com: "{{ admin_email }}"
  - postmaster@yourdomain.com: "{{ admin_email }}"
```

etc.
